2025-06-01 16:20:17,856 - __main__ - ERROR - Failed to register with bot: Cannot connect to host localhost:8080 ssl:default [Connect call failed ('127.0.0.1', 8080)]
2025-06-01 16:20:26,820 - __main__ - ERROR - Failed to send heartbeat: Cannot connect to host host.docker.internal:8000 ssl:default [Connect call failed ('172.17.0.1', 8000)]
2025-06-01 16:21:18,973 - __main__ - ERROR - Failed to register with bot: Cannot connect to host localhost:8080 ssl:default [Connect call failed ('127.0.0.1', 8080)]
2025-06-01 16:21:35,816 - __main__ - ERROR - Failed to send heartbeat: Cannot connect to host host.docker.internal:8000 ssl:default [Connect call failed ('172.17.0.1', 8000)]
2025-06-01 16:21:43,971 - api.routes - ERROR - Failed to get worker info: cannot access local variable 'socket' where it is not associated with a value
2025-06-01 16:21:44,028 - services.command_executor - ERROR - Command execution error: [Errno 2] No such file or directory: 'uptime'
2025-06-01 16:21:44,028 - services.command_executor - ERROR - Command execution failed: [Errno 2] No such file or directory: 'uptime'
2025-06-01 16:22:13,919 - __main__ - ERROR - Failed to send heartbeat: Cannot connect to host host.docker.internal:8000 ssl:default [Connect call failed ('172.17.0.1', 8000)]
2025-06-01 16:22:52,022 - __main__ - ERROR - Failed to send heartbeat: Cannot connect to host host.docker.internal:8000 ssl:default [Connect call failed ('172.17.0.1', 8000)]
